filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/sgr-agent/*.log
    fields:
      service: sgr-agent-backend
      environment: production
    fields_under_root: true
    json.keys_under_root: true
    json.add_error_key: true
    multiline.pattern: '^\{'
    multiline.negate: true
    multiline.match: after

  - type: container
    enabled: true
    paths:
      - '/var/lib/docker/containers/*/*.log'
    processors:
      - add_docker_metadata:
          host: "unix:///var/run/docker.sock"

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_docker_metadata: ~
  - drop_fields:
      fields: ["agent.ephemeral_id", "agent.id", "agent.name", "agent.version", "ecs.version", "host.architecture", "host.os.build", "host.os.codename", "host.os.family", "host.os.kernel", "host.os.name", "host.os.platform", "host.os.version", "log.offset"]

output.elasticsearch:
  hosts: ["${ELASTICSEARCH_HOSTS:http://elasticsearch:9200}"]
  username: "${ELASTICSEARCH_USERNAME:}"
  password: "${ELASTICSEARCH_PASSWORD:}"
  index: "sgr-agent-logs-%{+yyyy.MM.dd}"

setup.template.settings:
  index.number_of_shards: 1
  index.codec: best_compression

setup.ilm.enabled: true
setup.ilm.rollover_alias: "sgr-agent-logs"
setup.ilm.pattern: "{now/d}-000001"

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644
