"""Initial migration

Revision ID: d9809eeeef7a
Revises: 
Create Date: 2026-01-18 20:52:58.338573

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd9809eeeef7a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('UPLOADED', 'PROCESSING', 'DOCUMENT_LOADED', 'TEXT_EXTRACTED', 'DATA_EXTRACTED', 'VALIDATION_PASSED', 'VALIDATION_FAILED', 'CHECKING_1C', 'CREATING_IN_1C', 'COMPLETED', 'FAILED', name='processingstate'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_contracts_created_at', 'contracts', ['created_at'], unique=False)
    op.create_index('idx_contracts_status', 'contracts', ['status'], unique=False)
    op.create_index(op.f('ix_contracts_id'), 'contracts', ['id'], unique=False)
    op.create_index(op.f('ix_contracts_status'), 'contracts', ['status'], unique=False)
    op.create_index(op.f('ix_contracts_uuid'), 'contracts', ['uuid'], unique=True)
    op.create_table('contract_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('inn', sa.String(length=12), nullable=False),
    sa.Column('kpp', sa.String(length=9), nullable=True),
    sa.Column('legal_entity_type', sa.Enum('LEGAL', 'INDIVIDUAL', name='legalentitytype'), nullable=False),
    sa.Column('full_name', sa.String(length=500), nullable=False),
    sa.Column('short_name', sa.String(length=300), nullable=True),
    sa.Column('organizational_form', sa.String(length=100), nullable=True),
    sa.Column('gov_com_type', sa.Enum('GOVERNMENT', 'COMMERCIAL', name='govcomtype'), nullable=True),
    sa.Column('is_supplier', sa.Boolean(), nullable=True),
    sa.Column('is_buyer', sa.Boolean(), nullable=True),
    sa.Column('contract_name', sa.String(length=500), nullable=True),
    sa.Column('contract_number', sa.String(length=50), nullable=True),
    sa.Column('contract_date', sa.Date(), nullable=True),
    sa.Column('contract_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vat_percent', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('vat_type', sa.Enum('WITHOUT', 'INCLUDED', 'ADDITIONAL', name='vattype'), nullable=True),
    sa.Column('service_description', sa.Text(), nullable=True),
    sa.Column('service_start_date', sa.Date(), nullable=True),
    sa.Column('service_end_date', sa.Date(), nullable=True),
    sa.Column('locations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('responsible_persons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('payment_terms', sa.Text(), nullable=True),
    sa.Column('specification_exists', sa.Boolean(), nullable=True),
    sa.Column('pricing_method', sa.Text(), nullable=True),
    sa.Column('acceptance_procedure', sa.Text(), nullable=True),
    sa.Column('reporting_forms', sa.Text(), nullable=True),
    sa.Column('task_execution_term', sa.String(length=100), nullable=True),
    sa.Column('additional_conditions', sa.Text(), nullable=True),
    sa.Column('technical_info', sa.Text(), nullable=True),
    sa.Column('extraction_confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_contract_data_contract_id', 'contract_data', ['contract_id'], unique=False)
    op.create_index('idx_contract_data_inn', 'contract_data', ['inn'], unique=False)
    op.create_index(op.f('ix_contract_data_contract_id'), 'contract_data', ['contract_id'], unique=True)
    op.create_index(op.f('ix_contract_data_id'), 'contract_data', ['id'], unique=False)
    op.create_index(op.f('ix_contract_data_inn'), 'contract_data', ['inn'], unique=False)
    op.create_table('processing_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=True),
    sa.Column('event_status', sa.Enum('SUCCESS', 'WARNING', 'ERROR', name='eventstatus'), nullable=False),
    sa.Column('event_message', sa.Text(), nullable=True),
    sa.Column('event_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_processing_history_contract_id', 'processing_history', ['contract_id'], unique=False)
    op.create_index('idx_processing_history_event_type', 'processing_history', ['event_type'], unique=False)
    op.create_index(op.f('ix_processing_history_contract_id'), 'processing_history', ['contract_id'], unique=False)
    op.create_index(op.f('ix_processing_history_id'), 'processing_history', ['id'], unique=False)
    op.create_table('validation_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('test_case_id', sa.Integer(), nullable=True),
    sa.Column('test_case_name', sa.String(length=255), nullable=True),
    sa.Column('expected_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actual_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('match', sa.Boolean(), nullable=True),
    sa.Column('mismatched_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_validation_results_contract_id', 'validation_results', ['contract_id'], unique=False)
    op.create_index(op.f('ix_validation_results_contract_id'), 'validation_results', ['contract_id'], unique=False)
    op.create_index(op.f('ix_validation_results_id'), 'validation_results', ['id'], unique=False)
    op.create_table('counterparty_1c',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_data_id', sa.Integer(), nullable=False),
    sa.Column('entity_uuid', sa.String(length=36), nullable=True),
    sa.Column('entity_name', sa.String(length=255), nullable=True),
    sa.Column('status_1c', sa.Enum('CREATED', 'UPDATED', 'ERROR', name='onecstatus'), nullable=True),
    sa.Column('created_in_1c_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_from_1c', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_from_1c', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contract_data_id'], ['contract_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_counterparty_1c_contract_data_id'), 'counterparty_1c', ['contract_data_id'], unique=True)
    op.create_index(op.f('ix_counterparty_1c_id'), 'counterparty_1c', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_counterparty_1c_id'), table_name='counterparty_1c')
    op.drop_index(op.f('ix_counterparty_1c_contract_data_id'), table_name='counterparty_1c')
    op.drop_table('counterparty_1c')
    op.drop_index(op.f('ix_validation_results_id'), table_name='validation_results')
    op.drop_index(op.f('ix_validation_results_contract_id'), table_name='validation_results')
    op.drop_index('idx_validation_results_contract_id', table_name='validation_results')
    op.drop_table('validation_results')
    op.drop_index(op.f('ix_processing_history_id'), table_name='processing_history')
    op.drop_index(op.f('ix_processing_history_contract_id'), table_name='processing_history')
    op.drop_index('idx_processing_history_event_type', table_name='processing_history')
    op.drop_index('idx_processing_history_contract_id', table_name='processing_history')
    op.drop_table('processing_history')
    op.drop_index(op.f('ix_contract_data_inn'), table_name='contract_data')
    op.drop_index(op.f('ix_contract_data_id'), table_name='contract_data')
    op.drop_index(op.f('ix_contract_data_contract_id'), table_name='contract_data')
    op.drop_index('idx_contract_data_inn', table_name='contract_data')
    op.drop_index('idx_contract_data_contract_id', table_name='contract_data')
    op.drop_table('contract_data')
    op.drop_index(op.f('ix_contracts_uuid'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_status'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_id'), table_name='contracts')
    op.drop_index('idx_contracts_status', table_name='contracts')
    op.drop_index('idx_contracts_created_at', table_name='contracts')
    op.drop_table('contracts')
    # ### end Alembic commands ###
